import { createElement } from 'lwc';
import Doit_inpc_statusINPC_Opp from 'c/doit_inpc_statusINPC_Opp';

describe('c-doit-inpc-status-i-n-p-c-opp', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-doit-inpc-status-i-n-p-c-opp', {
            is: Doit_inpc_statusINPC_Opp
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});