import { createElement } from 'lwc';
import Doit_inpc_CreateINPCAsignation from 'c/doit_inpc_CreateINPCAsignation';

describe('c-doit-inpc-create-inpc-asignation', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-doit-inpc-create-inpc-asignation', {
            is: Doit_inpc_CreateINPCAsignation
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});